MODEL:
  NUM_CLASSES: 3
INPUT:
  IMAGE_SIZE: 300
DATASETS:
  TRAIN: ("voc_2007_trainval", )
  TEST: ("voc_2007_test", )
SOLVER:
  MAX_ITER: 10000
  LR_STEPS: [8000, 9000]
  GAMMA: 0.1
  BATCH_SIZE: 16
  LR: 1e-3

OUTPUT_DIR: 'outputs/vgg_ssd300_voc0712'